name: TTCraft
version: 1.3.3
main: com.kirik.ttcraft.main.TTCraft
api-version: 1.19
authors: [Kazzius]
description: Paper Plugin for Theta Tau Minecraft Server
commands:
  banish:
  help:
  home:
  kick:
  sethome:
  setlevel:
  setnick:
  setspawn:
  smite:
  spawn:
  summon:
  test:
  tp:
