name: TTCraft
version: 1.2.2
main: com.kirik.ttcraft.main.TTCraft
api-version: 1.19
authors: [Kazzius]
description: Paper Plugin for Theta Tau Minecraft Server
commands:
  setnick:
    description: Sets (or resets) nickname of the player
    usage: /setnick <nickname|reset> (color codes start with $)
  test:
    description: Test command
    usage: /test
  help:
    description: Lists available commands
    usage: /help
  setlevel:
    description: Sets the level of another player
    usage: /setlevel <player> <level>
  smite:
    description: Smite a player (visually)
    usage: /smite <player>
  sethome:
    description: Sets home of the player
    usage: /sethome
  home:
    description: Teleports player to their home
    usage: /home