name: TTCraft
version: 1.3.2
main: com.kirik.ttcraft.main.TTCraft
api-version: 1.19
authors: [Kazzius]
description: Paper Plugin for Theta Tau Minecraft Server
commands:
  setnick:
  test:
  help:
  setlevel:
  smite:
  sethome:
  home:
  spawn:
  setspawn:
  tp:
  summon:
  banish: