name: TTCraft
version: 1.2
main: com.kirik.ttcraft.main.TTCraft
api-version: 1.19
authors: [Kazzius]
description: Paper Plugin for Theta Tau Minecraft Server
commands:
  setnick:
    description: Sets nickname of the player
    usage: /setnick <nickname|reset> (color codes start with $)
  test:
    description: Test command
    usage: /test